teams = {
	#Big East
	'Pirates': 'Seton Hall University',
	'Villanova Wildcats': 'Villanova University',
	'St. John\'s University eSports': 'St. John\'s University',
	'DePaul Blue Demons': 'DePaul University',
	'Georgetown Reflection': 'Georgetown University',
	'Butler University': 'Butler University',
	'Butler Premier': 'Butler University',
	'Marquette University': 'Marquette University',
	'Providence College': 'Providence College',
	#Big Sky
	'Hornets': 'California State University, Sacramento',
	'Claw Gaming': 'Weber State University',
	'UM Griz': 'University of Montana',
	'Montana State University, Bozeman - Bobcats': 'Montana State University',
	'Eagle Gaming': 'Eastern Washington University',
	'NAU LumberJax': 'Northern Arizona University',
	'Vikings': 'Portland State University',
	'Thunderbird Esports': 'Southern Utah University',
	'UNCO Gold ': 'University of Northern Colorado',
	#East Coast Conference
	'Daemen College eSports': 'Daemen College',
	'Spartans': 'St. Thomas Aquinas College',
	'Mavericks': 'Mercy College',
	'SNHU Esports': 'Southern New Hampshire University',
	'Farmingdale Rams green': 'Farmingdale State College',
	'Molloy College Esports': 'Molloy College',
	'New York Tech Cybears': 'New York Institute of Technology',
	'St. Joseph\'s (L.I.)': 'Saint Joseph\'s College (Long Island)',
	#East Coast Athletic Conference
	'UAlbany eSports': 'SUNY Albany',
	'Thomas Esports': 'Thomas College',
	'King Tornado': 'King University',
	'Caldwell University': 'Caldwell University',
	'Alfred State Esports': 'SUNY Alfred State',
	'SHU eSports: LoL': 'Sacred Heart University',
	'Rams': 'ECPI University',
	'Rider Broncs': 'Rider University',
	'Golden Knights': 'Saint Rose College',
	'RPI League of Legends': 'Rensselaer Polytechnic Institute',
	'Stockton Esports': 'Stockton University',
	'Goose Nation': 'Washington College',
	'Keuka Wolves': 'Keuka College',
	'Roos': 'SUNY Canton',
	'Sharks': 'Long Island University',
	'Red Flash': 'Saint Francis University',
	'Stevenson Esports': 'Stevenson University',
	#Landmark Conference
	'Eagles': 'Juniata College',
	'Cardinal Esports': 'Catholic University of America',
	'Team Forest': 'Drew University',
	'Goucher Gophers': 'Goucher College',
	'Blue Jays': 'Elizabethtown College',
	#Metro Atlantic Athletic Conference
	'Niagara University': 'Niagara University',
	'Red Foxes': 'Marist College',
	'Quinnipiac Bobcats': 'Quinnipiac University',
	'Peacocks': 'Saint Peter\'s University',
	'Canisius College': 'Canisius College',
	'Siena Saints': 'Siena College',
	#Midwest Esports Conference
	'RMU Esports': 'Robert Morris University Illinois',
	'Illinois College': 'Illinois College',
	'Grand View Vikings ': 'Grand View University',
	'Drury University': 'Drury University',
	'Shockers': 'Wichita State University',
	'Mizzou Esports': 'University of Missouri',
	'Midland Warriors': 'Midland University',
	#Mountain West Conference
	'NVE Blue': 'University of Nevada, Reno',
	'Spartan Esports': 'San Jose State University',
	'UNLV Esports': 'University of Nevada, Las Vegas',
	'University of New Mexico': 'University of New Mexico',
	'Utah State Aggies': 'Utah State',
	'CSU Rams': 'Colorado State University',
	'SDSU Varsity': 'San Diego State University',
	'UH Warriors': 'University of Hawai\'i at Mānoa',
	'Fresno State Esports': 'California State University, Fresno',
	'UWYO Esports': 'University of Wyoming',
	'USAFA': 'United States Air Force Academy',
	'Broncos': 'Boise State University',
	#Peach Belt Conference
	'Bearcat Bytes': 'Lander University',
	'HSU Reddies': 'Henderson State University',
	'Clayton State Lakers': 'Clayton State University',
	'Coker Cobras': 'Coker University',
	'Young Harris College': 'Young Harris College',
	'USCA Pacers': 'University of South Carolina Aiken',
	'Mocs': 'Florida Southern College',
	'Bobcats': 'Georgia College & State University',
	'Alma College Esports ': 'Alma College',
	'Augusta University Jags': 'Augusta University',
	'UNG Esports ': 'University of North Georgia',
	'Montevallo Esports': 'University of Montevallo',
	'CSU Cougars': 'Columbus State University',
	'Flagler College Saints ': 'Flagler College',
	'Shark Squad': 'Hawaii Pacific University',
	'Georgia Southwestern E-Sports': 'Georgia Southwestern State University',
	#West Coast Conference
	'USF Dons Esports A': 'University of San Francisco',
	'Tigers': 'University of the Pacific',
	'Torero Gaming': 'University of San Diego',
	'Pepperdine Esports': 'Pepperdine University',
	'Pilots': 'University of Portland',
	'Crimson Lions': 'Loyola Marymount University',
	#Esports Collegiate Conference
	'UB Esports': 'SUNY Buffalo',
	'OU Bobcats': 'Ohio University',
	'Kent State Varsity': 'Kent State University',
	'WMU Esports': 'Western Michigan University',
	'CMU': 'Central Michigan University',
	'UToledo Esports': 'University of Toledo',
	'Akron Zips Gold': 'University of Akron',
	'Miami University RedHawks': 'Miami University',
	'BGSU Falcons': 'Bowling Green State University',
	'EMU Esports': 'Eastern Michigan University',
	'NIU Esports': 'Northern Illinois University',
	'Ball State University': 'Ball State University',
}